### ISSUE TITLE
Extend #23 to convert the device identifier to an integer value

### ISSUE THREAD

**Issue by vatbub** [vatbub/common#25]

**Comment by vatbub** [comment]
#23

**Comment by vatbub** [comment]
murmur3_32 does not seem to always return 32 bit integers

**Comment by vatbub** [comment]
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.ArithmeticException: BigInteger out of int range
        at java.math.BigInteger.intValueExact(Unknown Source)
        at com.github.vatbub.common.core.Common.getUniqueDeviceIdentifierAsDecInt(Common.java:456)
        at view.MainWindow.main(MainWindow.java:290)
        ... 11 more```

**Comment by vatbub** [comment]
It still seems to fail sometimes (e. g. with the following crc32c hash: `e6238cb2`)

**Comment by vatbub** [comment]
Short summary: The overall problem seems to not have been the actual hashing, but the conversion from a `BigInteger` to `int`. Apparently, `BigInteger` sometimes refuses to convert itself into an int even if it could. Now using `Integer.parseInt(hash, 16)` which seems to be better
